

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - .:/app
    env_file:
      - .env

    environment:
      DATABASE_URL: ${DATABASE_URL}

    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: daniilramkulov
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge
